ultron:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200  

  # Position Controllers ---------------------------------------
  joint1_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint1
  joint2_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint2
  joint3_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint3
  joint4_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint4
  joint5_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint5
  joint6_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint6
